### ISSUE TITLE
Spahn / Villa

### ISSUE THREAD

**Issue by georgloesel** [transparenzunion/transparenzunion.github.io#15]
# Um welchen Sachverhalt handelt es sich:

neue Erkenntnisse zum Fall Spahn / Villa 

# Ich beziehe mich auf folgenden Link / Inhalt:

https://www.tagesspiegel.de/politik/gute-bankverbindung-so-konnte-spahn-seine-millionenteure-berliner-villa-bezahlen/27094262.html

# Mein Änderungs- / Ergänzungswunsch ist:

# Diese Referenzen, bevorzugt als Link, existieren zum Sachverhalt:

https://www.tagesspiegel.de/politik/gute-bankverbindung-so-konnte-spahn-seine-millionenteure-berliner-villa-bezahlen/27094262.html

**Comment by 324rsdf** [comment]
Dazu auch:

https://www.tagesspiegel.de/politik/berichterstattung-haette-nicht-verboten-werden-duerfen-gericht-stuft-spahns-villenkauf-als-politisches-thema-ein/27133754.html
