### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Nghi93** [transparenzunion/transparenzunion.github.io#24]
# Um welchen Sachverhalt handelt es sich:
Generell fehlt der ganze Wirecard Skandal rund um Merkel, Altmaier, Amthor.

# Ich beziehe mich auf folgenden Link / Inhalt:
https://www.sueddeutsche.de/politik/wirecard-untersuchungsausschuss-peter-altmaier-dorothee-baer-1.5270933?utm_source=emarsys&sc_lid=189687076&utm_content=sz.de/1.5270933&utm_campaign=SZ_am_Morgen_210421&sc_llid=74662&utm_medium=email&sc_src=email_2368557&sc_uid=BYIvXRdXEt

# Mein Änderungs- / Ergänzungswunsch ist:

# Diese Referenzen, bevorzugt als Link, existieren zum Sachverhalt:

**Comment by raphting** [comment]
Vielen Dank fürs Einreichen!
Clankriminalitaet beschäftigt sich mit einzelnen PolitikerInnen und nicht mit übergeordneten Sachverhalten.
Amthor und Guttenberg sind in diesem Zusammenhang aufgelistet. Falls Du konkret etwas zu einem Politiker oder einer Politikerin hast, mache gerne ein neues Ticket auf :)
Die Aussagen von Bär und Altmaier sind rätselhaft, reichen für einen vollständigen Artikel noch nicht aus. In diesem Zusammenhang lass uns noch warten, bis tatsächlich ein Fall von Korruption bekannt wird.
