### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EnRic0111** [transparenzunion/transparenzunion.github.io#42]
# Um welchen Sachverhalt handelt es sich:

Burkhard Mende (Toll Collect) ist neuer Geschäftsführer der MiG (Mobilfunkinfrastrukturgesellschaft) geworden. Diese Tochtergesellschaft von Toll Collect wurde im Auftrag des Verkehrsministers gründet, um den Mobilfunk in Deutschland voran zu treiben. Diese neue Gesellschaft besteht bisher nur aus 2 Geschäftsführer mit je 190.000€ Gehalt ohne das dieses Unternehmen bisher je was geleistet hat. Zufälliger ist es das Unternehmen, welches für die nicht vorhandene PKW Maut hunderte Millionen vom Verkehrsministerium dank Scheuer erhalten soll bzw erhielt. Ich weiß nicht, warum dieser Mensch immer noch auf den Posten sitzt, Wahnsinn.

# Ich beziehe mich auf folgenden Link / Inhalt:

[https://www.wiwo.de/politik/deutschland/mobilfunk-wen-interessieren-schon-190-000-euro-brutto/26919758.html](url)
[https://www.rnd.de/wirtschaft/scheuers-funklochagentur-hat-erst-zwei-stellen-besetzt-die-der-geschaeftsfuehrer-OSHKF74DCFHEVJOT2W4VWZKIBE.html](url)
[https://www.reddit.com/r/de/comments/o06mje/scheuers_funklochagentur_hat_erst_zwei_stellen/h1ttxn2/?context=3](url)
[https://www.welt.de/politik/deutschland/article215626288/Andreas-Scheuers-Maut-Debakel-Die-Rolle-von-Toll-Collect.html](url)

# Mein Änderungs- / Ergänzungswunsch ist:

# Diese Referenzen, bevorzugt als Link, existieren zum Sachverhalt:

**Comment by raphting** [comment]
Ein interessanter Fall! Ich kann hier jedoch, außer den vermutlich überzogenen Geschäftsführergehältern, keine Bereicherung im Sinne von Korruption erkennen. Das Potenzial für Interpretationen des Falls ist natürlich hoch. Aus meiner Sicht ist es allerdings nicht ausreichend belegt.
