### ISSUE TITLE
Laschet Finanzamt

### ISSUE THREAD

**Issue by Ronin275** [transparenzunion/transparenzunion.github.io#43]
# Um welchen Sachverhalt handelt es sich:

# Ich beziehe mich auf folgenden Link / Inhalt:
https://www.sueddeutsche.de/politik/cdu-nordrhein-westfalen-das-falsch-verbuchte-buch-von-armin-laschet-1.2525618
# Mein Änderungs- / Ergänzungswunsch ist:

# Diese Referenzen, bevorzugt als Link, existieren zum Sachverhalt:

**Comment by 324rsdf** [comment]
https://www.clankriminalitaet.de/2015/06/16/laschet-buch.html
