### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by GigaDive** [transparenzunion/transparenzunion.github.io#47]
# Um welchen Sachverhalt handelt es sich:
Zeitleiste um 2018 - 2013 - 2015 - 2012 , Reihenfolge ändern. Oder ist das so gewollt? Bzw. nach Publikationsdatum sortiert?
# Ich beziehe mich auf folgenden Link / Inhalt:
https://www.clankriminalitaet.de/
# Mein Änderungs- / Ergänzungswunsch ist:
Reihenfolge klären.
# Diese Referenzen, bevorzugt als Link, existieren zum Sachverhalt:

**Comment by 324rsdf** [comment]
Danke für den Hinweis, ist gefixt!
